services:
  - type: web
    name: bmt-anime-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000